### ISSUE TITLE
[REFACTOR] 페어프로그래밍을 통한 버그 수정

### ISSUE THREAD

**Issue by psw9999** [woowa-techcamp-2022/android-repo-05#72]
## 목적
- 현재 발견되는 버그를 페어프로그래밍으로 수정한다.

## 작업 상세 내용
- [x] SearchActivity EditText 엔터 누르면 줄바꿈 되는 현상
- [x] SearchActivity 검색 로딩 중 "결과 없음"이 보이는 현상
- [x] SearchActivity visibility 데이터바인딩화
- [x] #76

**Comment by HwiChance** [comment]
테스트 용 코멘트
